<div class="pagination-container" id="${paginationId}">
    <div class="pagination-content">
        <a href="javascript:_paginationJump('${paginationId}', 'first')">首页</a>
        <a href="javascript:_paginationJump('${paginationId}', 'prev')">上一页</a>
        <a href="javascript:_paginationJump('${paginationId}', 'next')">下一页</a>
        <a href="javascript:_paginationJump('${paginationId}', 'last')">尾页</a>
        <span class="pagination-data">当前第<span class="current-page">1</span>页，共<span class="total-page">0</span>页，<span class="total-count">0</span>条数据</span>
    </div>
</div>